baseURL = "https://www.jyunko.cn/"
languageCode = "zh-cn"
title = "HsiangNianian (ç®€å¾‹çº¯)"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true
Copyright = "Â© 2023 <a href='https://academic.jyunko.cn'>ACA H.N.</a>"

[params]
  author = "ç®€å¾‹çº¯"
  description = "Arranger, yeah I have an idea, programming with musical language and composing with programming language :s "
  github = "HsiangNianian"
  Education = "@AICMUniversity"
  email = "i@jyunko.cn"
  url = "https://www.jyunko.cn"
  keywords = "blog, google analytics"
  rss = false
  lastmod = true
  favicon = "/images/github.png"
  location = "China"
  userStatusEmoji = "ğŸ™ƒ"
  enableGitalk = false
  
  [params.Highlights]
  dev = true
    
  [params.gitalk]
    clientID = "1b969db3bd6439c3a48e" # Your client ID
    clientSecret = "0e896f862715e20b91315e92064d8798664aa6f1" # Your client secret
    repo = "github-style" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "HsiangNianian" # æ‚¨çš„GitHub ID
    admin = "HsiangNianian" # æ‚¨çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token=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" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†
  [[params.links]]
    title = "AICMU"
    href = "https://github.com/AICMUniversity"
    icon = "https://ghproxy.com/github.com/AICMUniversity/.github/blob/main/profile/logo.svg"
  [[params.links]]
    title = "ACA Jyunko"
    href = "https://academic.jyunko.cn"
    icon = "https://academic.jyunko.cn/assets/Erigit.png"
  [[params.links]]
    title = "Retrofor"
    href = "https://github.com/retrofor"
    icon = "https://iamai.retrofor.space/retro.png"
  [[params.links]]
    title = "æ°´ç³»"
    href = "https://github.com/HydroRoll-Team"
    icon = "https://mirror.ghproxy.com/https://raw.githubusercontent.com/HydroRoll-Team/HydroRoll/main/site/src/assets/image/logo.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
